# Generated by Django 4.1.7 on 2023-03-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_unlock_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="unlock_date",
            field=models.DateField(default=None, null=True),
        ),
    ]
