# Generated by Django 4.1.7 on 2023-03-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0003_alter_book_book_genders"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gender",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
